use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegionCatalog {
    regions: Vec<RegionDefinition>,
    direct_aliases: BTreeMap<String, String>,
    group_aliases: BTreeMap<String, Vec<String>>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RegionDefinition {
    id: String,
    label: String,
    sensor_code: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let catalog_path = manifest_dir.join("src/regions.catalog.json");
    println!("cargo:rerun-if-changed={}", catalog_path.display());

    let catalog_json = fs::read_to_string(&catalog_path).expect("failed to read region catalog");
    let catalog: RegionCatalog =
        serde_json::from_str(&catalog_json).expect("failed to parse region catalog");
    validate_catalog(&catalog);

    let generated = render_catalog(&catalog);
    let out_path =
        PathBuf::from(env::var("OUT_DIR").expect("missing out dir")).join("regions_generated.rs");
    fs::write(out_path, generated).expect("failed to write generated region tables");
}

fn validate_catalog(catalog: &RegionCatalog) {
    let region_ids = catalog
        .regions
        .iter()
        .map(|region| region.id.as_str())
        .collect::<BTreeSet<_>>();
    if region_ids.len() != catalog.regions.len() {
        panic!("region catalog contains duplicate region ids");
    }

    let sensor_codes = catalog
        .regions
        .iter()
        .map(|region| region.sensor_code.as_str())
        .collect::<BTreeSet<_>>();
    if sensor_codes.len() != catalog.regions.len() {
        panic!("region catalog contains duplicate sensor codes");
    }

    if catalog
        .direct_aliases
        .keys()
        .any(|alias| catalog.group_aliases.contains_key(alias))
    {
        panic!("region catalog alias is present in both direct_aliases and group_aliases");
    }

    for canonical_region in catalog.direct_aliases.values() {
        if !region_ids.contains(canonical_region.as_str()) {
            panic!("unknown direct alias target: {canonical_region}");
        }
    }

    for (alias, grouped_regions) in &catalog.group_aliases {
        if grouped_regions.is_empty() {
            panic!("group alias {alias} cannot be empty");
        }

        for canonical_region in grouped_regions {
            if !region_ids.contains(canonical_region.as_str()) {
                panic!("unknown grouped alias target: {canonical_region}");
            }
        }
    }
}

fn render_catalog(catalog: &RegionCatalog) -> String {
    let mut generated = String::from("// generated by crates/scemas-core/build.rs\n");

    for region in &catalog.regions {
        generated.push_str(&format!(
            "pub const {}: &str = {};\n",
            to_const_name(&region.id),
            rust_string(&region.id),
        ));
    }
    generated.push('\n');

    generated.push_str("pub const CANONICAL_REGION_IDS: &[&str] = &[\n");
    for region in &catalog.regions {
        generated.push_str(&format!("    {},\n", to_const_name(&region.id)));
    }
    generated.push_str("];\n\n");

    generated.push_str("pub fn region_label(zone: &str) -> Option<&'static str> {\n");
    generated.push_str("    match zone {\n");
    for region in &catalog.regions {
        generated.push_str(&format!(
            "        {} => Some({}),\n",
            to_const_name(&region.id),
            rust_string(&region.label),
        ));
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n\n");

    generated.push_str("fn generated_direct_zone_alias(zone: &str) -> Option<&'static str> {\n");
    generated.push_str("    match zone {\n");
    for (alias, canonical_region) in &catalog.direct_aliases {
        generated.push_str(&format!(
            "        {} => Some({}),\n",
            rust_string(alias),
            to_const_name(canonical_region),
        ));
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n\n");

    generated.push_str(
        "fn generated_grouped_zone_alias(zone: &str) -> Option<&'static [&'static str]> {\n",
    );
    generated.push_str("    match zone {\n");
    for (alias, grouped_regions) in &catalog.group_aliases {
        let canonical_regions = grouped_regions
            .iter()
            .map(|region| to_const_name(region))
            .collect::<Vec<_>>()
            .join(", ");
        generated.push_str(&format!(
            "        {} => Some(&[{}]),\n",
            rust_string(alias),
            canonical_regions,
        ));
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n\n");

    generated.push_str(
        "fn generated_canonical_zone_for_sensor_code(zone_code: &str) -> Option<&'static str> {\n",
    );
    generated.push_str("    match zone_code {\n");
    for region in &catalog.regions {
        generated.push_str(&format!(
            "        {} => Some({}),\n",
            rust_string(&region.sensor_code),
            to_const_name(&region.id),
        ));
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");

    generated
}

fn to_const_name(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            'a'..='z' | 'A'..='Z' | '0'..='9' => character.to_ascii_uppercase(),
            _ => '_',
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}
