use std::{env, fs, path::PathBuf, process::Command};

const DESKTOP_ONLY_SCHEMA_SQL: &str = r#"
-- desktop-only tables (not in @scemas/db)
CREATE TABLE IF NOT EXISTS sync_queue (
    id BIGSERIAL PRIMARY KEY,
    command TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS sync_queue_status_created_at_idx
    ON sync_queue (status, created_at);
"#;

fn clean_stale_pg_bundle() -> std::io::Result<()> {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir must exist"));
    let target_dir = out_dir
        .parent()
        .and_then(|path| path.parent())
        .and_then(|path| path.parent())
        .expect("tauri out dir must live under target/<profile>/build");
    let bundled_pg_dir = target_dir.join("resources").join("pg");

    if bundled_pg_dir.exists() {
        fs::remove_dir_all(bundled_pg_dir)?;
    }

    Ok(())
}

fn materialize_schema_snapshot() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo manifest dir must exist"));
    let db_dir = manifest_dir.join("../../packages/db");
    let schema_source = db_dir.join("src/schema.ts");
    let drizzle_config = db_dir.join("drizzle.config.ts");
    let schema_path = manifest_dir.join("resources/schema.sql");

    println!("cargo:rerun-if-changed={}", schema_source.display());
    println!("cargo:rerun-if-changed={}", drizzle_config.display());

    let output = Command::new("bun")
        .args([
            "x",
            "drizzle-kit",
            "export",
            "--config",
            "drizzle.config.ts",
        ])
        .current_dir(&db_dir)
        .output()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("failed to export drizzle schema: {stderr}").into());
    }

    let mut schema = String::from(
        "-- auto-generated by crates/scemas-desktop/build.rs from @scemas/db schema\n\n",
    );
    schema.push_str(&String::from_utf8(output.stdout)?);
    if !schema.ends_with('\n') {
        schema.push('\n');
    }
    schema.push('\n');

    schema.push_str(DESKTOP_ONLY_SCHEMA_SQL);
    schema.push('\n');

    let existing = fs::read_to_string(&schema_path).ok();
    if existing.as_deref() != Some(schema.as_str()) {
        fs::create_dir_all(
            schema_path
                .parent()
                .expect("schema snapshot should have a parent directory"),
        )?;
        fs::write(&schema_path, schema)?;
    }

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    clean_stale_pg_bundle()?;
    materialize_schema_snapshot()?;
    tauri_build::build();
    Ok(())
}
